# API Gateway Configuration






# CORS Configuration
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}


# Redis Configuration
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.timeout=60000

# Rate Limiting Configuration
spring.cloud.gateway.filter.request-rate-limiter.redis-rate-limiter.replenishRate=100
spring.cloud.gateway.filter.request-rate-limiter.redis-rate-limiter.burstCapacity=150
spring.cloud.gateway.filter.request-rate-limiter.redis-rate-limiter.requestedTokens=1

# RabbitMQ Configuration
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

# JWT Configuration
jwt.secret=${JWT_SECRET}

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,gateway,prometheus
management.endpoint.health.show-details=always

# Swagger UI Aggregation
springdoc.swagger-ui.urls[0].name=User Service
springdoc.swagger-ui.urls[0].url=/v3/api-docs/user-service
springdoc.swagger-ui.urls[1].name=Payment Service
springdoc.swagger-ui.urls[1].url=/v3/api-docs/payment-service
springdoc.swagger-ui.urls[2].name=Operator Service
springdoc.swagger-ui.urls[2].url=/v3/api-docs/operator-service
springdoc.swagger-ui.urls[3].name=Recharge Service
springdoc.swagger-ui.urls[3].url=/v3/api-docs/recharge-service
springdoc.swagger-ui.urls[4].name=Notification Service
springdoc.swagger-ui.urls[4].url=/v3/api-docs/notification-service
