server.port=8761
spring.application.name=discovery-server
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://config-server:8888}

# Eureka Server Config
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=true

# RabbitMQ for Spring Cloud Bus
spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
