name: Backend CD

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        service: [
          'user-service',
          'operator-service',
          'recharge-service',
          'payment-service',
          'notification-service',
          'api-gateway',
          'discovery-server',
          'config-server'
        ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B clean package -DskipTests --file ${{ matrix.service }}/pom.xml

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}
        tags: |
          type=ref,event=branch
          type=semver,pattern={{version}}
          type=sha

    - name: Copy config-repo (for config-server only)
      if: matrix.service == 'config-server'
      run: cp -r config-repo config-server/config-repo

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./${{ matrix.service }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
